-- Data Ops -- which addresses a dossier is about (ClientApp #333, part C).
--
-- Until now an address existed in the review lane only as a side effect of a
-- value: extraction_field.address_text is what the report wrote, address_id
-- what the Worker's resolveAddress() made of it. Nothing said "these are the
-- addresses of this dossier", so a reviewer could not accept one, refuse one
-- ("this address is not part of this dossier" -- Don's ruling, 2026-09-11),
-- add one the pipeline missed, or move a value from Molenwal 59 to 59A. And a
-- report about a block of eight houses produced a rapportage about one.
--
-- This table is that list. One row per (dossier, address):
--
--   source   pipeline -- the Worker resolved it from the document (part D
--                       writes these at ingest; until then the API materialises
--                       a row the first time a reviewer decides on the address)
--            reviewer -- added by hand in the Studio
--            melder   -- the address the submission was filed under
--   state    pending   -- proposed, no decision yet
--            confirmed -- belongs to this dossier: gets a sample on commit,
--                         even without values (the reviewer fills it in)
--            rejected  -- does not belong to this dossier: its open values are
--                         superseded and it never becomes a sample
--
-- Values keep their own address_id; this row is the decision about the
-- address itself. The dossier's own pand (dossier.building_id) is not a row
-- here -- it stays where it is, and the API shows it at the top of the list.
--
-- The API also gains two column writes it did not have: moving a value to
-- another address (extraction_field.address_id/address_text) and correcting
-- the pand a dossier was filed under (dossier.building_id/resolution_status).
--
-- Additive. Reversible with one DROP and two REVOKEs.
--
--   psql "$DB_URL" -f sql/migrate/create_dataops_dossier_address.sql

BEGIN;

CREATE TABLE IF NOT EXISTS dataops.dossier_address (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dossier_id   bigint NOT NULL REFERENCES dataops.dossier(id) ON DELETE CASCADE,
    address_id   geocoder.geocoder_id NOT NULL REFERENCES geocoder.address(id),
    -- The address as the document wrote it, when the pipeline found it there.
    -- Null on an address added by hand.
    address_text text,
    source       dataops.actor_kind NOT NULL,
    state        dataops.review_state NOT NULL DEFAULT 'pending',
    decided_by   uuid,
    decided_at   timestamptz,
    note         text,
    created_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT dossier_address_once UNIQUE (dossier_id, address_id),
    CONSTRAINT dossier_address_state_check CHECK (state IN ('pending', 'confirmed', 'rejected')),
    CONSTRAINT dossier_address_source_check CHECK (source IN ('pipeline', 'reviewer', 'melder'))
);

COMMENT ON TABLE dataops.dossier_address IS
  'The addresses a dossier is about, and what the reviewer decided about each (ClientApp #333 part C). A value''s own address_id says where the value was read; this row says whether that address belongs to the dossier at all.';
COMMENT ON COLUMN dataops.dossier_address.address_text IS 'The address as the document wrote it, when the pipeline found it there. Null when added by hand.';
COMMENT ON COLUMN dataops.dossier_address.source IS 'pipeline (resolved from the document) | reviewer (added by hand) | melder (the submission''s own address).';
COMMENT ON COLUMN dataops.dossier_address.state IS 'pending (no decision) | confirmed (belongs to the dossier; a sample on commit) | rejected (not part of this dossier; its values are superseded).';

CREATE INDEX IF NOT EXISTS dossier_address_dossier_idx ON dataops.dossier_address (dossier_id);

-- The API is the only writer today. Part D (Worker) will add pipeline rows at
-- ingest and needs INSERT then; that grant travels with that change.
GRANT SELECT, INSERT, UPDATE, DELETE ON dataops.dossier_address TO fundermaps_webapp;
GRANT USAGE ON SEQUENCE dataops.dossier_address_id_seq TO fundermaps_webapp;
GRANT SELECT ON dataops.dossier_address TO fundermaps_windmill;

-- Moving a value to another address, and correcting the pand the dossier was
-- filed under. Both are reviewer actions; both were impossible for the API.
GRANT UPDATE (address_id, address_text) ON dataops.extraction_field TO fundermaps_webapp;
GRANT UPDATE (building_id, resolution_status) ON dataops.dossier TO fundermaps_webapp;

COMMIT;
