-- Data Ops -- the send log for melder-facing mail (tracker FunderMaps #1020).
--
-- The intake form promises "Wij sturen een bevestiging naar {email}" and, until
-- FunderMapsApi feat/intake-mail, nothing ever sent one: 23 upload dossiers
-- since 2026-08-27 were told a mail would come. The API now mails at two
-- moments -- the ontvangstbevestiging right after `POST /api/intake/dossier`
-- commits, and the afronding when a reviewer closes or commits the dossier.
--
-- This table is what makes that idempotent. Both outcome writers
-- (`POST /dataops/dossier/:id/outcome` and `POST /dataops/dossier/:id/commit`)
-- can run for the same dossier, a bulk close can overlap an earlier one, and
-- an HTTP retry can replay any of them. The API claims the (dossier, kind)
-- row BEFORE it talks to Resend; whoever finds the row already there does
-- nothing. #1020 asked for exactly this: "idempotent, per dossier een
-- verzendlog".
--
--   kind     received | closed
--   status   pending  -- claimed, send in flight (or the process died mid-send)
--            sent     -- Resend accepted it; provider_id is its message id
--            failed   -- Resend refused or was unreachable; error says why.
--                        A failed row is re-claimed by the next call, so a
--                        transport hiccup is not the last word.
--
-- Additive. Reversible with one DROP. Not folded into schema.sql: none of
-- dataops.* is there yet (see sql/migrate/README.md).
--
--   psql "$DB_URL" -f sql/migrate/create_dataops_dossier_mail.sql

BEGIN;

CREATE TABLE IF NOT EXISTS dataops.dossier_mail (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dossier_id  bigint NOT NULL REFERENCES dataops.dossier(id) ON DELETE CASCADE,
    kind        text NOT NULL CHECK (kind IN ('received', 'closed')),
    recipient   text NOT NULL,
    subject     text NOT NULL,
    status      text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'failed')),
    provider_id text,
    error       text,
    created_at  timestamptz NOT NULL DEFAULT now(),
    sent_at     timestamptz,
    -- One mail per moment per dossier. This constraint IS the idempotency.
    CONSTRAINT dossier_mail_once UNIQUE (dossier_id, kind)
);

COMMENT ON TABLE dataops.dossier_mail IS
  'Send log for melder-facing mail (#1020). One row per (dossier, kind), claimed before the send; the unique key is the idempotency guard.';
COMMENT ON COLUMN dataops.dossier_mail.kind IS 'received (ontvangstbevestiging) | closed (afronding).';
COMMENT ON COLUMN dataops.dossier_mail.status IS 'pending | sent | failed. A failed row is re-claimed on the next attempt.';
COMMENT ON COLUMN dataops.dossier_mail.provider_id IS 'Resend message id, when sent.';
COMMENT ON COLUMN dataops.dossier_mail.recipient IS 'Address the mail went to. Personal data, like dossier.submitter.';

-- The API is the only writer: it claims the row (INSERT ... ON CONFLICT DO
-- UPDATE, hence UPDATE as well) and records the result.
GRANT SELECT, INSERT, UPDATE ON dataops.dossier_mail TO fundermaps_webapp;

COMMIT;
