-- Phase K: rename geocoder.building.is_active → active.
--
-- Boolean naming consistency: is_active was the only is_* boolean
-- column in the schema. Every other boolean (27 of them) uses no
-- prefix (chained_building, foundation_recovery, neighbor_recovery,
-- enabled, etc.). Drop the prefix to align with the majority.
--
-- Coordinated with code changes:
--   * C# entity Building.IsActive → Active (+ test fixture)
--   * Worker SQL load_building.sql (5 refs in INSERT col lists,
--     UPDATE SET, and WHERE clauses)
--   * WebFront Building.ts class + IBuilding.ts interface
--   * Report Building.ts class + IBuilding.ts interface
--
-- Wire format goes from `isActive` (camelCase from PascalCase
-- IsActive) to `active`. Frontend interfaces + classes renamed in
-- lockstep so that's not a runtime issue.
--
-- ALTER TABLE RENAME COLUMN is metadata-only.
-- Run as: fundermaps (owner)

ALTER TABLE geocoder.building RENAME COLUMN is_active TO active;
