-- Phase G: rename application.mapset_collection.options → metadata.
--
-- Sibling tables (mapset, organization_mapset) already use the
-- "metadata" column name for the same concept. This brings
-- mapset_collection in line.
--
-- Coordinated full-stack rename (Option B):
--   * C# entity Mapset.Options → Metadata
--   * 3 SQL refs in MapsetRepository
--   * TS API Drizzle field options → metadata
--   * WebFront IMapset.options → metadata, IMapsetFE.options → metadata,
--     mapMapset() local var, useMapCenterManagement.ts (4 refs)
--   * Report repo: same shape (interfaces + service)
--
-- Wire format changes from `options` (JSON string) to `metadata`
-- (JSON string). Both old and new frontend builds will read the
-- field correctly because the wire-string is just a key name —
-- TypeScript compile-time check ensures backend + frontend rename
-- together.
--
-- Run as: fundermaps (owner)

ALTER TABLE application.mapset_collection RENAME COLUMN options TO metadata;
