-- Seed data for public.model_gevelscan + public.risk_table_priority.
-- These are static lookup tables that drive maplayer.facade_scan. They
-- live in the public schema today; the long-term plan is to move them
-- into a FunderMaps schema (likely 'data') — see project_public_model_tables_relocate.
--
-- Loaded by scripts/init_db.sh after schema.sql so the table structure
-- exists before INSERTs run.

INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('nil', 'none', 'nil', 'a');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('nil', 'none', 'small', 'a');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('nil', 'none', 'mediocre', 'a');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('nil', 'none', 'big', 'a');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('nil', 'none', 'very_big', 'a');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('nil', 'nil', 'nil', 'a');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('nil', 'nil', 'small', 'a');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('nil', 'nil', 'mediocre', 'a');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('nil', 'nil', 'big', 'b');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('nil', 'nil', 'very_big', 'b');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('nil', 'small', 'nil', 'b');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('nil', 'small', 'small', 'b');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('nil', 'small', 'mediocre', 'b');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('nil', 'small', 'big', 'b');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('nil', 'small', 'very_big', 'b');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('nil', 'mediocre', 'nil', 'b');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('nil', 'mediocre', 'small', 'b');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('nil', 'mediocre', 'mediocre', 'b');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('nil', 'mediocre', 'big', 'b');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('nil', 'mediocre', 'very_big', 'b');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('nil', 'big', 'nil', 'c');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('nil', 'big', 'small', 'c');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('nil', 'big', 'mediocre', 'c');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('nil', 'big', 'big', 'c');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('nil', 'big', 'very_big', 'c');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('small', 'none', 'nil', 'c');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('small', 'none', 'small', 'c');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('small', 'none', 'mediocre', 'c');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('small', 'none', 'big', 'c');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('small', 'none', 'very_big', 'c');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('small', 'nil', 'nil', 'c');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('small', 'nil', 'small', 'c');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('small', 'nil', 'mediocre', 'c');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('small', 'nil', 'big', 'c');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('small', 'nil', 'very_big', 'c');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('small', 'small', 'nil', 'c');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('small', 'small', 'small', 'c');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('small', 'small', 'mediocre', 'c');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('small', 'small', 'big', 'c');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('small', 'small', 'very_big', 'c');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('small', 'mediocre', 'nil', 'd');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('small', 'mediocre', 'small', 'd');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('small', 'mediocre', 'mediocre', 'd');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('small', 'mediocre', 'big', 'd');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('small', 'mediocre', 'very_big', 'd');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('small', 'big', 'nil', 'd');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('small', 'big', 'small', 'd');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('small', 'big', 'mediocre', 'd');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('small', 'big', 'big', 'd');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('small', 'big', 'very_big', 'd');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('mediocre', 'none', 'nil', 'd');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('mediocre', 'none', 'small', 'd');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('mediocre', 'none', 'mediocre', 'd');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('mediocre', 'none', 'big', 'd');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('mediocre', 'none', 'very_big', 'd');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('mediocre', 'nil', 'nil', 'd');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('mediocre', 'nil', 'small', 'd');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('mediocre', 'nil', 'mediocre', 'd');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('mediocre', 'nil', 'big', 'd');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('mediocre', 'nil', 'very_big', 'd');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('mediocre', 'small', 'nil', 'd');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('mediocre', 'small', 'small', 'd');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('mediocre', 'small', 'mediocre', 'd');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('mediocre', 'small', 'big', 'd');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('mediocre', 'small', 'very_big', 'd');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('mediocre', 'mediocre', 'nil', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('mediocre', 'mediocre', 'small', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('mediocre', 'mediocre', 'mediocre', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('mediocre', 'mediocre', 'big', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('mediocre', 'mediocre', 'very_big', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('mediocre', 'big', 'nil', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('mediocre', 'big', 'small', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('mediocre', 'big', 'mediocre', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('mediocre', 'big', 'big', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('mediocre', 'big', 'very_big', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('big', 'none', 'nil', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('big', 'none', 'small', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('big', 'none', 'mediocre', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('big', 'none', 'big', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('big', 'none', 'very_big', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('big', 'nil', 'nil', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('big', 'nil', 'small', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('big', 'nil', 'mediocre', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('big', 'nil', 'big', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('big', 'nil', 'very_big', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('big', 'small', 'nil', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('big', 'small', 'small', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('big', 'small', 'mediocre', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('big', 'small', 'big', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('big', 'small', 'very_big', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('big', 'mediocre', 'nil', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('big', 'mediocre', 'small', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('big', 'mediocre', 'mediocre', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('big', 'mediocre', 'big', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('big', 'mediocre', 'very_big', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('big', 'big', 'nil', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('big', 'big', 'small', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('big', 'big', 'mediocre', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('big', 'big', 'big', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('big', 'big', 'very_big', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('very_big', 'none', 'nil', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('very_big', 'none', 'small', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('very_big', 'none', 'mediocre', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('very_big', 'none', 'big', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('very_big', 'none', 'very_big', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('very_big', 'nil', 'nil', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('very_big', 'nil', 'small', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('very_big', 'nil', 'mediocre', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('very_big', 'nil', 'big', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('very_big', 'nil', 'very_big', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('very_big', 'small', 'nil', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('very_big', 'small', 'small', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('very_big', 'small', 'mediocre', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('very_big', 'small', 'big', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('very_big', 'small', 'very_big', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('very_big', 'mediocre', 'nil', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('very_big', 'mediocre', 'small', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('very_big', 'mediocre', 'mediocre', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('very_big', 'mediocre', 'big', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('very_big', 'mediocre', 'very_big', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('very_big', 'big', 'nil', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('very_big', 'big', 'small', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('very_big', 'big', 'mediocre', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('very_big', 'big', 'big', 'e');
INSERT INTO public.model_gevelscan (skewed_parallel, facade_type, skewed_perpendicular, risk) VALUES ('very_big', 'big', 'very_big', 'e');
INSERT INTO public.risk_table_priority (risk, settlement_speed, priority) VALUES ('a', 'nil', 'Very Low');
INSERT INTO public.risk_table_priority (risk, settlement_speed, priority) VALUES ('a', 'small', 'Very Low');
INSERT INTO public.risk_table_priority (risk, settlement_speed, priority) VALUES ('a', 'mediocre', 'Low');
INSERT INTO public.risk_table_priority (risk, settlement_speed, priority) VALUES ('a', 'big', 'Medium');
INSERT INTO public.risk_table_priority (risk, settlement_speed, priority) VALUES ('a', 'very_big', 'High');
INSERT INTO public.risk_table_priority (risk, settlement_speed, priority) VALUES ('b', 'nil', 'Very Low');
INSERT INTO public.risk_table_priority (risk, settlement_speed, priority) VALUES ('b', 'small', 'Low');
INSERT INTO public.risk_table_priority (risk, settlement_speed, priority) VALUES ('b', 'mediocre', 'Medium');
INSERT INTO public.risk_table_priority (risk, settlement_speed, priority) VALUES ('b', 'big', 'Medium');
INSERT INTO public.risk_table_priority (risk, settlement_speed, priority) VALUES ('b', 'very_big', 'High');
INSERT INTO public.risk_table_priority (risk, settlement_speed, priority) VALUES ('c', 'nil', 'Low');
INSERT INTO public.risk_table_priority (risk, settlement_speed, priority) VALUES ('c', 'small', 'Medium');
INSERT INTO public.risk_table_priority (risk, settlement_speed, priority) VALUES ('c', 'mediocre', 'Medium');
INSERT INTO public.risk_table_priority (risk, settlement_speed, priority) VALUES ('c', 'big', 'High');
INSERT INTO public.risk_table_priority (risk, settlement_speed, priority) VALUES ('c', 'very_big', 'High');
INSERT INTO public.risk_table_priority (risk, settlement_speed, priority) VALUES ('d', 'nil', 'Medium');
INSERT INTO public.risk_table_priority (risk, settlement_speed, priority) VALUES ('d', 'small', 'Medium');
INSERT INTO public.risk_table_priority (risk, settlement_speed, priority) VALUES ('d', 'mediocre', 'High');
INSERT INTO public.risk_table_priority (risk, settlement_speed, priority) VALUES ('d', 'big', 'Urgent');
INSERT INTO public.risk_table_priority (risk, settlement_speed, priority) VALUES ('d', 'very_big', 'Very Urgent');
INSERT INTO public.risk_table_priority (risk, settlement_speed, priority) VALUES ('e', 'nil', 'High');
INSERT INTO public.risk_table_priority (risk, settlement_speed, priority) VALUES ('e', 'small', 'High');
INSERT INTO public.risk_table_priority (risk, settlement_speed, priority) VALUES ('e', 'mediocre', 'Urgent');
INSERT INTO public.risk_table_priority (risk, settlement_speed, priority) VALUES ('e', 'big', 'Very Urgent');
INSERT INTO public.risk_table_priority (risk, settlement_speed, priority) VALUES ('e', 'very_big', 'Very Urgent');
